// <auto-generated />
using System;
using Calciolandia_Website.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Calciolandia_Website.Core.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Calciolandia_Website.Core.Data.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("FootballClubId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("FootballClubId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("35e824bf-a9ff-4dfa-9cd7-e0bb181ee50a"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "bd06493c-2941-478a-b347-af64542cf964",
                            Email = "m_fvidenov@abv.bg",
                            EmailConfirmed = true,
                            FirstName = "Mihail",
                            FootballClubId = 5,
                            LastName = "Videnov",
                            LockoutEnabled = false,
                            NormalizedEmail = "m_fvidenov@abv.bg",
                            NormalizedUserName = "mishaka002",
                            PasswordHash = "AQAAAAEAACcQAAAAEEWysyqrve35NRkGyOn0/x03Ray5XPUWZ92oubGpp1k/9IcO+j513QYhgBSZhVOqXw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "425a98be-1b21-4136-b1ca-f0c8e6ba4c80",
                            TwoFactorEnabled = false,
                            UserName = "mishaka002"
                        },
                        new
                        {
                            Id = new Guid("37390eb1-f3f7-45ee-835f-9712488e3aa5"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "aa5ad2d1-b7d3-4cfc-91d5-22b9da383f0a",
                            Email = "luben_6@abv.bg",
                            EmailConfirmed = true,
                            FirstName = "Luben",
                            FootballClubId = 7,
                            LastName = "Videnov",
                            LockoutEnabled = false,
                            NormalizedEmail = "luben_6@abv.bg",
                            NormalizedUserName = "luben_v",
                            PasswordHash = "AQAAAAEAACcQAAAAEBWdVtqgpMxdSmWyX+1Ot0dlsY/bFmI+9xidYWATDiDVd5PoCRsTOZF3pxBQUA/vlQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "044c46a9-07a6-4b16-9707-28bb221d472f",
                            TwoFactorEnabled = false,
                            UserName = "luben_v"
                        });
                });

            modelBuilder.Entity("Calciolandia_Website.Core.Data.Models.Fixture", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AwayTeamId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HomeTeamId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("LeagueId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Round")
                        .HasColumnType("int");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("StadiumId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("LeagueId");

                    b.HasIndex("StadiumId");

                    b.ToTable("Fixtures");

                    b.HasData(
                        new
                        {
                            Id = new Guid("43a79872-0c0a-4fd6-9675-7198708ce662"),
                            AwayTeamId = 11,
                            Date = new DateTime(2024, 4, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeTeamId = 7,
                            IsDeleted = false,
                            LeagueId = 1,
                            Result = "0 - 1",
                            Round = 33,
                            Season = "2023/2024",
                            StadiumId = 9,
                            Time = "19:30"
                        },
                        new
                        {
                            Id = new Guid("38130c98-accb-4e0a-818a-5f47d2b08dc9"),
                            AwayTeamId = 10,
                            Date = new DateTime(2024, 4, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeTeamId = 3,
                            IsDeleted = false,
                            LeagueId = 1,
                            Result = "2 - 2",
                            Round = 33,
                            Season = "2023/2024",
                            StadiumId = 5,
                            Time = "21:45"
                        });
                });

            modelBuilder.Entity("Calciolandia_Website.Core.Data.Models.FootballClub", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("FoundedYear")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("LeagueId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("LogoImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("StadiumId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("Trophies")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId");

                    b.HasIndex("StadiumId");

                    b.ToTable("FootballClubs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Zingonia - Corso Europa 20040 Bergamo Italy",
                            City = "Bergamo",
                            FoundedYear = 1907,
                            IsDeleted = false,
                            LeagueId = 1,
                            LogoImageUrl = "https://img.legaseriea.it/vimages/62cfd69d/atalanta.png?webp&q=70&size=300x-",
                            Name = "Atalanta BC",
                            Nickname = "La Dea",
                            StadiumId = 3,
                            Trophies = 0
                        },
                        new
                        {
                            Id = 2,
                            Address = "Via Casteldebole 10 40132 Bologna Italy",
                            City = "Bologna",
                            FoundedYear = 1909,
                            IsDeleted = false,
                            LeagueId = 1,
                            LogoImageUrl = "https://img.legaseriea.it/vimages/62cef3f6/bologna.png?webp&q=70&size=300x-",
                            Name = "Bologna FC 1909",
                            Nickname = "Rossoblù",
                            StadiumId = 4,
                            Trophies = 7
                        },
                        new
                        {
                            Id = 3,
                            Address = "Via Mameli 106 09123 Cagliari Italy",
                            City = "Cagliari",
                            FoundedYear = 1907,
                            IsDeleted = false,
                            LeagueId = 1,
                            LogoImageUrl = "https://img.legaseriea.it/vimages/62cfd202/cagliari.png?webp&q=70&size=300x-",
                            Name = "Cagliari Calcio",
                            Nickname = "Rossoblù",
                            StadiumId = 5,
                            Trophies = 1
                        },
                        new
                        {
                            Id = 4,
                            Address = "Via di Pianezzoli 50053 Empoli Italy",
                            City = "Empoli",
                            FoundedYear = 1907,
                            IsDeleted = false,
                            LeagueId = 1,
                            LogoImageUrl = "https://img.legaseriea.it/vimages/62cef42e/empoli.png?webp&q=70&size=300x-",
                            Name = "FC Empoli",
                            Nickname = "Azzurri",
                            StadiumId = 6,
                            Trophies = 0
                        },
                        new
                        {
                            Id = 5,
                            Address = " Viale Manfredo Fanti, 4 50137 Firenze Italy",
                            City = "Florence",
                            FoundedYear = 1907,
                            IsDeleted = false,
                            LeagueId = 1,
                            LogoImageUrl = "https://img.legaseriea.it/vimages/62cef452/fiorentina.png?webp&q=70&size=300x-",
                            Name = "ACF Fiorentina",
                            Nickname = "Viola",
                            StadiumId = 7,
                            Trophies = 2
                        },
                        new
                        {
                            Id = 6,
                            Address = "Viale Olimpia 03100 Frosinone Italy",
                            City = "Frosinone",
                            FoundedYear = 1907,
                            IsDeleted = false,
                            LeagueId = 1,
                            LogoImageUrl = "https://img.legaseriea.it/vimages/62cfdfec/frosinone.png?webp&q=70&size=300x-",
                            Name = "Frosinone Calcio",
                            Nickname = "Giallazzurri",
                            StadiumId = 8,
                            Trophies = 0
                        },
                        new
                        {
                            Id = 7,
                            Address = "Via Ronchi 67 16155 Genova Italy",
                            City = "Genoa",
                            FoundedYear = 1907,
                            IsDeleted = false,
                            LeagueId = 1,
                            LogoImageUrl = "https://img.legaseriea.it/vimages/649e8a06/GENOA-1.png?webp&q=70&size=300x-",
                            Name = "Genoa CFC",
                            Nickname = "Grifone",
                            StadiumId = 9,
                            Trophies = 9
                        },
                        new
                        {
                            Id = 8,
                            Address = "Via Torricelli 37 37136 Verona Italy",
                            City = "Verona",
                            FoundedYear = 1907,
                            IsDeleted = false,
                            LeagueId = 1,
                            LogoImageUrl = "https://img.legaseriea.it/vimages/62cef475/colore=YELLOW.png?webp&q=70&size=300x-",
                            Name = "Hellas Verona FC",
                            Nickname = "Gialloblu",
                            StadiumId = 10,
                            Trophies = 1
                        },
                        new
                        {
                            Id = 9,
                            Address = "Viale della Liberazione Milano Italy",
                            City = "Milan",
                            FoundedYear = 1907,
                            IsDeleted = false,
                            LeagueId = 1,
                            LogoImageUrl = "https://img.legaseriea.it/vimages/62cef496/inter.png?webp&q=70&size=300x-",
                            Name = "Inter Milan",
                            Nickname = "Nerazzurri",
                            StadiumId = 1,
                            Trophies = 19
                        },
                        new
                        {
                            Id = 10,
                            Address = "Via Druento, 175 10151 Torino Italy",
                            City = "Turin",
                            FoundedYear = 1907,
                            IsDeleted = false,
                            LeagueId = 1,
                            LogoImageUrl = "https://img.legaseriea.it/vimages/62cef4b7/colore=WHITE.png?webp&q=70&size=300x-",
                            Name = "Juventus FC",
                            Nickname = "Bianconeri",
                            StadiumId = 11,
                            Trophies = 36
                        },
                        new
                        {
                            Id = 11,
                            Address = "Via di Santa Cornelia 1000 00060 Roma Italy",
                            City = "Rome",
                            FoundedYear = 1907,
                            IsDeleted = false,
                            LeagueId = 1,
                            LogoImageUrl = "https://img.legaseriea.it/vimages/62cef4d5/lazio.png?webp&q=70&size=300x-",
                            Name = "SS Lazio",
                            Nickname = "Biancocelesti",
                            StadiumId = 2,
                            Trophies = 2
                        },
                        new
                        {
                            Id = 12,
                            Address = "Colonello Archimede Costadura 3 73100 Lecce Italy",
                            City = "Lecce",
                            FoundedYear = 1907,
                            IsDeleted = false,
                            LeagueId = 1,
                            LogoImageUrl = "https://img.legaseriea.it/vimages/62cef4f6/lecce.png?webp&q=70&size=300x-",
                            Name = "US Lecce",
                            Nickname = "Giallorossi",
                            StadiumId = 12,
                            Trophies = 0
                        },
                        new
                        {
                            Id = 13,
                            Address = "Via Aldo Rossi 8 20149 Milano Italy",
                            City = "Milan",
                            FoundedYear = 1907,
                            IsDeleted = false,
                            LeagueId = 1,
                            LogoImageUrl = "https://img.legaseriea.it/vimages/62cef513/milan.png?webp&q=70&size=300x-",
                            Name = "AC Milan",
                            Nickname = "Rossoneri",
                            StadiumId = 1,
                            Trophies = 19
                        },
                        new
                        {
                            Id = 14,
                            Address = "Via Ragazzi del '99, 14 20900 Monza Italy",
                            City = "Monza",
                            FoundedYear = 1907,
                            IsDeleted = false,
                            LeagueId = 1,
                            LogoImageUrl = "https://img.legaseriea.it/vimages/62c6acbd/monza.png?webp&q=70&size=300x-",
                            Name = "AC Monza",
                            Nickname = "Biancorossi",
                            StadiumId = 13,
                            Trophies = 0
                        },
                        new
                        {
                            Id = 15,
                            Address = "Via del Maio di Porto 9 80133 Napoli Italy",
                            City = "Naples",
                            FoundedYear = 1907,
                            IsDeleted = false,
                            LeagueId = 1,
                            LogoImageUrl = "https://img.legaseriea.it/vimages/62cef532/napoli.png?webp&q=70&size=300x-",
                            Name = "SSC Napoli",
                            Nickname = "Partenopei",
                            StadiumId = 14,
                            Trophies = 3
                        },
                        new
                        {
                            Id = 16,
                            Address = "Piazzale Dino Viola 1 00128 Roma Italy",
                            City = "Rome",
                            FoundedYear = 1907,
                            IsDeleted = false,
                            LeagueId = 1,
                            LogoImageUrl = "https://img.legaseriea.it/vimages/62cfd5ce/roma.png?webp&q=70&size=300x-",
                            Name = "AS Roma",
                            Nickname = "Giallorossi",
                            StadiumId = 2,
                            Trophies = 3
                        },
                        new
                        {
                            Id = 17,
                            Address = "Via Salvador Allende 84131 Salerno Italy",
                            City = "Salerno",
                            FoundedYear = 1907,
                            IsDeleted = false,
                            LeagueId = 1,
                            LogoImageUrl = "https://img.legaseriea.it/vimages/62cef553/salernitana.png?webp&q=70&size=300x-",
                            Name = "US Salernitana 1919",
                            Nickname = "Granata",
                            StadiumId = 15,
                            Trophies = 0
                        },
                        new
                        {
                            Id = 18,
                            Address = "Piazza Risorgimento 47 41049 Sassuolo Italy",
                            City = "Sassuolo",
                            FoundedYear = 1907,
                            IsDeleted = false,
                            LeagueId = 1,
                            LogoImageUrl = "https://img.legaseriea.it/vimages/62cef590/sassuolo.png?webp&q=70&size=300x-",
                            Name = "US Sassuolo Calcio",
                            Nickname = "Neroverdi",
                            StadiumId = 16,
                            Trophies = 0
                        },
                        new
                        {
                            Id = 19,
                            Address = "Via Arcivescovado 1 10121 Torino Italy",
                            City = "Turin",
                            FoundedYear = 1907,
                            IsDeleted = false,
                            LeagueId = 1,
                            LogoImageUrl = "https://img.legaseriea.it/vimages/62cef5cb/torino.png?webp&q=70&size=300x-",
                            Name = "Torino FC",
                            Nickname = "Toro",
                            StadiumId = 17,
                            Trophies = 7
                        },
                        new
                        {
                            Id = 20,
                            Address = "Via A. e A. Candolini 2 33100 Udine Italy",
                            City = "Udine",
                            FoundedYear = 1907,
                            IsDeleted = false,
                            LeagueId = 1,
                            LogoImageUrl = "https://img.legaseriea.it/vimages/62cef5e9/udinese.png?webp&q=70&size=300x-",
                            Name = "Udinese Calcio",
                            Nickname = "Friulani",
                            StadiumId = 18,
                            Trophies = 0
                        });
                });

            modelBuilder.Entity("Calciolandia_Website.Core.Data.Models.League", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LogoImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Leagues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "Italy",
                            IsDeleted = false,
                            LogoImageUrl = "https://tmssl.akamaized.net/images/logo/header/it1.png?lm=1656073460",
                            Name = "Serie A"
                        },
                        new
                        {
                            Id = 2,
                            Country = "Italy",
                            IsDeleted = false,
                            LogoImageUrl = "https://tmssl.akamaized.net/images/logo/header/it2.png?lm=1548242827",
                            Name = "Serie B"
                        },
                        new
                        {
                            Id = 3,
                            Country = "Italy",
                            IsDeleted = false,
                            LogoImageUrl = "https://tmssl.akamaized.net/images/logo/header/it3a.png?lm=1599832650",
                            Name = "Serie C"
                        });
                });

            modelBuilder.Entity("Calciolandia_Website.Core.Data.Models.Manager", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ContractExpiredDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ContractSignedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("FootballClubId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("FootballClubId");

                    b.ToTable("Managers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7596dcb1-be28-4810-894f-0d108c4746ad"),
                            Age = 57,
                            BirthDate = new DateTime(1965, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractExpiredDate = new DateTime(2025, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractSignedDate = new DateTime(2019, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Stefano",
                            FootballClubId = 13,
                            ImageUrl = "https://img.a.transfermarkt.technology/portrait/big/2135-1663977168.jpg?lm=1",
                            IsDeleted = false,
                            LastName = "Pioli",
                            Nationality = "Italy"
                        },
                        new
                        {
                            Id = new Guid("0343df0b-cf7b-4ea1-b22e-b5d1b37d6b01"),
                            Age = 55,
                            BirthDate = new DateTime(1968, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractExpiredDate = new DateTime(2024, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractSignedDate = new DateTime(2024, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Francesco",
                            FootballClubId = 15,
                            ImageUrl = "https://img.a.transfermarkt.technology/portrait/big/33804-1697643746.jpg?lm=1",
                            IsDeleted = false,
                            LastName = "Calzona",
                            Nationality = "Italy"
                        },
                        new
                        {
                            Id = new Guid("db0ccb79-686a-4756-b769-46a7291d781f"),
                            Age = 55,
                            BirthDate = new DateTime(1967, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractExpiredDate = new DateTime(2025, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractSignedDate = new DateTime(2021, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Massimiliano",
                            FootballClubId = 10,
                            ImageUrl = "https://img.a.transfermarkt.technology/portrait/big/7671-1663973141.jpg?lm=1",
                            IsDeleted = false,
                            LastName = "Allegri",
                            Nationality = "Italy"
                        },
                        new
                        {
                            Id = new Guid("ed8a8072-57bd-4e2a-a751-1b4550228ab9"),
                            Age = 47,
                            BirthDate = new DateTime(1976, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractExpiredDate = new DateTime(2024, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractSignedDate = new DateTime(2021, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Simone",
                            FootballClubId = 9,
                            ImageUrl = "https://img.a.transfermarkt.technology/portrait/big/21624-1663979865.jpg?lm=1",
                            IsDeleted = false,
                            LastName = "Inzaghi",
                            Nationality = "Italy"
                        },
                        new
                        {
                            Id = new Guid("c91969c6-bcfa-48ae-8795-908277ae4abf"),
                            Age = 65,
                            BirthDate = new DateTime(1958, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractExpiredDate = new DateTime(2024, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractSignedDate = new DateTime(2016, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Gian Piero",
                            FootballClubId = 1,
                            ImageUrl = "https://img.a.transfermarkt.technology/portrait/big/3436-1663862210.jpg?lm=1",
                            IsDeleted = false,
                            LastName = "Gasperini",
                            Nationality = "Italy"
                        },
                        new
                        {
                            Id = new Guid("188a7590-3b45-40a5-bc4c-e660369bc2e5"),
                            Age = 40,
                            BirthDate = new DateTime(1983, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractExpiredDate = new DateTime(2024, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractSignedDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Daniele",
                            FootballClubId = 16,
                            ImageUrl = "https://img.a.transfermarkt.technology/portrait/big/90748-1616069982.jpg?lm=1",
                            IsDeleted = false,
                            LastName = "De Rossi",
                            Nationality = "Italy"
                        },
                        new
                        {
                            Id = new Guid("fe1bf65e-e8d6-4e6c-9bd4-552c4f483159"),
                            Age = 45,
                            BirthDate = new DateTime(1977, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractExpiredDate = new DateTime(2024, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractSignedDate = new DateTime(2021, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Vincenzo",
                            FootballClubId = 5,
                            ImageUrl = "https://img.a.transfermarkt.technology/portrait/big/47288-1663950225.jpg?lm=1",
                            IsDeleted = false,
                            LastName = "Italiano",
                            Nationality = "Italy"
                        },
                        new
                        {
                            Id = new Guid("871c26b3-c051-43ce-a662-db5571f69606"),
                            Age = 45,
                            BirthDate = new DateTime(1978, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractExpiredDate = new DateTime(2025, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractSignedDate = new DateTime(2024, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Igor",
                            FootballClubId = 11,
                            ImageUrl = "https://img.a.transfermarkt.technology/portrait/big/28632-1646406004.jpg?lm=1",
                            IsDeleted = false,
                            LastName = "Tudor",
                            Nationality = "Croatia"
                        },
                        new
                        {
                            Id = new Guid("0ac01812-5943-4e1e-af5a-0296e9dffb73"),
                            Age = 60,
                            BirthDate = new DateTime(1964, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractExpiredDate = new DateTime(2024, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractSignedDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Davide",
                            FootballClubId = 18,
                            ImageUrl = "https://img.a.transfermarkt.technology/portrait/big/3793-1631177487.jpg?lm=1",
                            IsDeleted = false,
                            LastName = "Ballardini",
                            Nationality = "Italy"
                        },
                        new
                        {
                            Id = new Guid("060dcb8f-8672-4425-b4ea-1cb5786470dc"),
                            Age = 48,
                            BirthDate = new DateTime(1975, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractExpiredDate = new DateTime(2024, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractSignedDate = new DateTime(2023, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Gabriele",
                            FootballClubId = 20,
                            ImageUrl = "https://img.a.transfermarkt.technology/portrait/big/31903-1639297579.jpg?lm=1",
                            IsDeleted = false,
                            LastName = "Cioffi",
                            Nationality = "Italy"
                        },
                        new
                        {
                            Id = new Guid("51125581-f439-4f2a-aa8c-2ea1e001df3c"),
                            Age = 40,
                            BirthDate = new DateTime(1982, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractExpiredDate = new DateTime(2024, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractSignedDate = new DateTime(2022, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Thiago",
                            FootballClubId = 2,
                            ImageUrl = "https://img.a.transfermarkt.technology/portrait/big/61868-1663936050.jpg?lm=1",
                            IsDeleted = false,
                            LastName = "Motta",
                            Nationality = "Italy/Brazil"
                        },
                        new
                        {
                            Id = new Guid("53c51138-aa94-4f3f-8e1b-c26a45d28f69"),
                            Age = 39,
                            BirthDate = new DateTime(1984, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractExpiredDate = new DateTime(2024, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractSignedDate = new DateTime(2022, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Raffaele",
                            FootballClubId = 14,
                            ImageUrl = "https://img.a.transfermarkt.technology/portrait/big/95674-1663872108.jpg?lm=1",
                            IsDeleted = false,
                            LastName = "Palladino",
                            Nationality = "Italy"
                        },
                        new
                        {
                            Id = new Guid("26c069ee-17cc-4f2c-8d80-88658cf99b3e"),
                            Age = 61,
                            BirthDate = new DateTime(1962, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractExpiredDate = new DateTime(2024, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractSignedDate = new DateTime(2024, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Stefano",
                            FootballClubId = 17,
                            ImageUrl = "https://img.a.transfermarkt.technology/portrait/big/2127-1634565915.jpg?lm=1",
                            IsDeleted = false,
                            LastName = "Colantuono",
                            Nationality = "Italy"
                        },
                        new
                        {
                            Id = new Guid("53e492a8-c95d-4b01-bc24-79c63939233c"),
                            Age = 41,
                            BirthDate = new DateTime(1982, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractExpiredDate = new DateTime(2025, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractSignedDate = new DateTime(2022, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Alberto",
                            FootballClubId = 7,
                            ImageUrl = "https://img.a.transfermarkt.technology/portrait/big/64045-1673622044.jpg?lm=1",
                            IsDeleted = false,
                            LastName = "Gilardino",
                            Nationality = "Italy"
                        },
                        new
                        {
                            Id = new Guid("fbb1b90a-a685-4120-ab28-858978bbd2a1"),
                            Age = 56,
                            BirthDate = new DateTime(1967, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractExpiredDate = new DateTime(2024, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractSignedDate = new DateTime(2024, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Luca",
                            FootballClubId = 12,
                            ImageUrl = "https://img.a.transfermarkt.technology/portrait/big/7521-1663926746.jpg?lm=1",
                            IsDeleted = false,
                            LastName = "Gotti",
                            Nationality = "Italy"
                        },
                        new
                        {
                            Id = new Guid("a72e3e49-4099-46e3-a389-8d1dae6c1961"),
                            Age = 51,
                            BirthDate = new DateTime(1973, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractExpiredDate = new DateTime(2024, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractSignedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Davide",
                            FootballClubId = 4,
                            ImageUrl = "https://img.a.transfermarkt.technology/portrait/big/14892-1644914474.png?lm=1",
                            IsDeleted = false,
                            LastName = "Nicola",
                            Nationality = "Italy"
                        },
                        new
                        {
                            Id = new Guid("64637af9-4047-4840-b202-a855a9414bc1"),
                            Age = 59,
                            BirthDate = new DateTime(1963, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractExpiredDate = new DateTime(2024, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractSignedDate = new DateTime(2023, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Marco",
                            FootballClubId = 8,
                            ImageUrl = "https://img.a.transfermarkt.technology/portrait/big/12015-1649752265.jpg?lm=1",
                            IsDeleted = false,
                            LastName = "Baroni",
                            Nationality = "Italy"
                        },
                        new
                        {
                            Id = new Guid("d6981722-772b-44c0-acf2-8ef5f411ea4c"),
                            Age = 71,
                            BirthDate = new DateTime(1951, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractExpiredDate = new DateTime(2025, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractSignedDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Claudio",
                            FootballClubId = 3,
                            ImageUrl = "https://img.a.transfermarkt.technology/portrait/big/456-1521199129.jpg?lm=1",
                            IsDeleted = false,
                            LastName = "Ranieri",
                            Nationality = "Italy"
                        },
                        new
                        {
                            Id = new Guid("c2fc6829-ee9e-4f13-86aa-f5b858f5d792"),
                            Age = 53,
                            BirthDate = new DateTime(1969, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractExpiredDate = new DateTime(2024, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractSignedDate = new DateTime(2023, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Eusebio",
                            FootballClubId = 6,
                            ImageUrl = "https://img.a.transfermarkt.technology/portrait/big/12924-1631177386.jpg?lm=1",
                            IsDeleted = false,
                            LastName = "Di Francesco",
                            Nationality = "Italy"
                        },
                        new
                        {
                            Id = new Guid("10b38ca7-9319-49c4-93a8-b49a371083b6"),
                            Age = 47,
                            BirthDate = new DateTime(1975, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractExpiredDate = new DateTime(2024, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractSignedDate = new DateTime(2021, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ivan",
                            FootballClubId = 19,
                            ImageUrl = "https://img.a.transfermarkt.technology/portrait/big/16508-1594718677.jpg?lm=1",
                            IsDeleted = false,
                            LastName = "Juric",
                            Nationality = "Croatia"
                        });
                });

            modelBuilder.Entity("Calciolandia_Website.Core.Data.Models.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ContractExpiredDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ContractSignedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("FootballClubId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MarketValue")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Number")
                        .HasColumnType("int");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("FootballClubId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = new Guid("721d0eb7-e122-425b-a808-33bb10a1493a"),
                            Age = 28,
                            BirthDate = new DateTime(1995, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractExpiredDate = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractSignedDate = new DateTime(2021, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mike",
                            FootballClubId = 13,
                            ImageUrl = "https://img.a.transfermarkt.technology/portrait/big/182906-1681459155.jpg?lm=1",
                            IsDeleted = false,
                            LastName = "Maignan",
                            MarketValue = "€45.00m",
                            Nationality = "France",
                            Number = 16,
                            Position = "Goalkeeper"
                        },
                        new
                        {
                            Id = new Guid("75e2d346-b8ad-4aa0-bfd2-33d3f6a83f55"),
                            Age = 31,
                            BirthDate = new DateTime(1992, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractExpiredDate = new DateTime(2027, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractSignedDate = new DateTime(2023, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Marco",
                            FootballClubId = 13,
                            ImageUrl = "https://img.a.transfermarkt.technology/portrait/big/199976-1661351013.jpg?lm=1",
                            IsDeleted = false,
                            LastName = "Sportiello",
                            MarketValue = "€1.50m",
                            Nationality = "Italy",
                            Number = 57,
                            Position = "Goalkeeper"
                        },
                        new
                        {
                            Id = new Guid("848e40e2-7ddf-4642-990c-6767b488120f"),
                            Age = 40,
                            BirthDate = new DateTime(1983, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractExpiredDate = new DateTime(2024, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractSignedDate = new DateTime(2021, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Antonio",
                            FootballClubId = 13,
                            ImageUrl = "https://img.a.transfermarkt.technology/portrait/big/22141-1663574908.jpg?lm=1",
                            IsDeleted = false,
                            LastName = "Mirante",
                            MarketValue = "€100k",
                            Nationality = "Italy",
                            Number = 83,
                            Position = "Goalkeeper"
                        },
                        new
                        {
                            Id = new Guid("1ea4137b-c356-403e-915a-926f52057afc"),
                            Age = 25,
                            BirthDate = new DateTime(1997, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractExpiredDate = new DateTime(2027, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractSignedDate = new DateTime(2021, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Fikayo",
                            FootballClubId = 13,
                            ImageUrl = "https://img.a.transfermarkt.technology/portrait/big/303254-1684856117.jpg?lm=1",
                            IsDeleted = false,
                            LastName = "Tomori",
                            MarketValue = "€40.00m",
                            Nationality = "England",
                            Number = 23,
                            Position = "Centre-Back"
                        },
                        new
                        {
                            Id = new Guid("10c6c12d-1b35-42bc-802a-6e88e84acd11"),
                            Age = 23,
                            BirthDate = new DateTime(2000, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractExpiredDate = new DateTime(2027, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractSignedDate = new DateTime(2020, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Pierre",
                            FootballClubId = 13,
                            ImageUrl = "https://img.a.transfermarkt.technology/portrait/big/585949-1684854558.jpg?lm=1",
                            IsDeleted = false,
                            LastName = "Kalulu",
                            MarketValue = "€30.00m",
                            Nationality = "France",
                            Number = 20,
                            Position = "Centre-Back"
                        },
                        new
                        {
                            Id = new Guid("2159a3fc-2173-46da-8960-c4ec703b1154"),
                            Age = 23,
                            BirthDate = new DateTime(2000, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractExpiredDate = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractSignedDate = new DateTime(2019, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Marco",
                            FootballClubId = 1,
                            ImageUrl = "https://img.a.transfermarkt.technology/portrait/big/459763-1598856203.jpg?lm=1",
                            IsDeleted = false,
                            LastName = "Carnesecchi",
                            MarketValue = "€13.00m",
                            Nationality = "Italy",
                            Number = 29,
                            Position = "Goalkeeper"
                        },
                        new
                        {
                            Id = new Guid("76b27127-2c65-47cf-9136-82c9eab274dd"),
                            Age = 29,
                            BirthDate = new DateTime(1994, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractExpiredDate = new DateTime(2025, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractSignedDate = new DateTime(2021, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Juan",
                            FootballClubId = 1,
                            ImageUrl = "https://img.a.transfermarkt.technology/portrait/big/242359-1663583047.jpg?lm=1",
                            IsDeleted = false,
                            LastName = "Musso",
                            MarketValue = "€8.00m",
                            Nationality = "Argentina",
                            Number = 1,
                            Position = "Goalkeeper"
                        },
                        new
                        {
                            Id = new Guid("18faea62-bacf-43d0-bc27-91ebe995b3d1"),
                            Age = 32,
                            BirthDate = new DateTime(1991, 4, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractExpiredDate = new DateTime(2024, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractSignedDate = new DateTime(2009, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Francesco",
                            FootballClubId = 1,
                            ImageUrl = "https://img.a.transfermarkt.technology/portrait/big/126634-1644234341.jpg?lm=1",
                            IsDeleted = false,
                            LastName = "Rossi",
                            MarketValue = "€100k",
                            Nationality = "Italy",
                            Number = 31,
                            Position = "Goalkeeper"
                        },
                        new
                        {
                            Id = new Guid("9d1abc71-bd4f-4348-9a84-8143aaec879c"),
                            Age = 19,
                            BirthDate = new DateTime(2003, 12, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractExpiredDate = new DateTime(2027, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractSignedDate = new DateTime(2021, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Giorgio",
                            FootballClubId = 1,
                            ImageUrl = "https://img.a.transfermarkt.technology/portrait/big/571604-1679479850.jpg?lm=1",
                            IsDeleted = false,
                            LastName = "Scalvini",
                            MarketValue = "€40.00m",
                            Nationality = "Italy",
                            Number = 42,
                            Position = "Centre-Back"
                        },
                        new
                        {
                            Id = new Guid("afb16257-fa10-451c-8541-591642792273"),
                            Age = 30,
                            BirthDate = new DateTime(1993, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractExpiredDate = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractSignedDate = new DateTime(2016, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Berat",
                            FootballClubId = 1,
                            ImageUrl = "https://img.a.transfermarkt.technology/portrait/big/165513-1663582842.jpg?lm=1",
                            IsDeleted = false,
                            LastName = "Djimsiti",
                            MarketValue = "€10.00m",
                            Nationality = "Albania",
                            Number = 19,
                            Position = "Centre-Back"
                        });
                });

            modelBuilder.Entity("Calciolandia_Website.Core.Data.Models.President", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("FootballClubId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("FootballClubId");

                    b.ToTable("Presidents");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f5c3e91e-4ab4-436e-a6b9-a31da4bb1da5"),
                            Age = 76,
                            BirthDate = new DateTime(1946, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Paolo",
                            FootballClubId = 13,
                            ImageUrl = "https://img.a.transfermarkt.technology/portrait/big/61951-1663977917.jpg?lm=1",
                            IsDeleted = false,
                            LastName = "Scaroni",
                            Nationality = "Italy"
                        },
                        new
                        {
                            Id = new Guid("9d8c7686-078a-4199-af4c-5678e6e1b19a"),
                            Age = 74,
                            BirthDate = new DateTime(1949, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Aurelio",
                            FootballClubId = 15,
                            ImageUrl = "https://img.a.transfermarkt.technology/portrait/big/12590-1663975832.jpg?lm=1",
                            IsDeleted = false,
                            LastName = "de Laurentis",
                            Nationality = "Italy"
                        },
                        new
                        {
                            Id = new Guid("01e8d9f6-9cb8-41dd-a56a-b2689ea8ae63"),
                            Age = 59,
                            BirthDate = new DateTime(1963, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Gianluca",
                            FootballClubId = 10,
                            ImageUrl = "https://img.a.transfermarkt.technology/portrait/big/112227-1675245583.jpg?lm=1",
                            IsDeleted = false,
                            LastName = "Ferrero",
                            Nationality = "Italy"
                        },
                        new
                        {
                            Id = new Guid("9292d3e2-9cdf-4e6a-b646-1de9a5023e40"),
                            Age = 58,
                            BirthDate = new DateTime(1965, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Dan",
                            FootballClubId = 16,
                            ImageUrl = "https://img.a.transfermarkt.technology/portrait/header/default.jpg?lm=1",
                            IsDeleted = false,
                            LastName = "Friedkin",
                            Nationality = "USA"
                        },
                        new
                        {
                            Id = new Guid("4f65253e-9756-4fdc-a7be-85e82456bd4c"),
                            Age = 31,
                            BirthDate = new DateTime(1991, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Steven",
                            FootballClubId = 9,
                            ImageUrl = "https://img.a.transfermarkt.technology/portrait/big/50590-1663979396.jpg?lm=1",
                            IsDeleted = false,
                            LastName = "Zhang",
                            Nationality = "China"
                        },
                        new
                        {
                            Id = new Guid("1eb8cc36-c42c-45fd-8c12-2f1f6a6422e9"),
                            Age = 70,
                            BirthDate = new DateTime(1953, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Antonio",
                            FootballClubId = 1,
                            ImageUrl = "https://img.a.transfermarkt.technology/portrait/big/13226-1554472586.jpg?lm=1",
                            IsDeleted = false,
                            LastName = "Percassi",
                            Nationality = "Italy"
                        },
                        new
                        {
                            Id = new Guid("06b45893-172c-4f65-82b9-7d1aa2b6a207"),
                            Age = 73,
                            BirthDate = new DateTime(1949, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Rocco",
                            FootballClubId = 5,
                            ImageUrl = "https://img.a.transfermarkt.technology/portrait/big/70038-1586856311.jpg?lm=1",
                            IsDeleted = false,
                            LastName = "Commisso",
                            Nationality = "USA"
                        },
                        new
                        {
                            Id = new Guid("5eea96dc-9ca6-4ec4-b269-7fe6a1fda61d"),
                            Age = 66,
                            BirthDate = new DateTime(1957, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Claudio",
                            FootballClubId = 11,
                            ImageUrl = "https://img.a.transfermarkt.technology/portrait/big/8685-1584712373.jpg?lm=1",
                            IsDeleted = false,
                            LastName = "Lotito",
                            Nationality = "Italy"
                        },
                        new
                        {
                            Id = new Guid("7a16dca4-ee2c-4512-ac46-b1085e84a569"),
                            Age = 66,
                            BirthDate = new DateTime(1957, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Urbano",
                            FootballClubId = 19,
                            ImageUrl = "https://img.a.transfermarkt.technology/portrait/big/13945-1663947949.jpg?lm=1",
                            IsDeleted = false,
                            LastName = "Cairo",
                            Nationality = "Italy"
                        },
                        new
                        {
                            Id = new Guid("cb01a8b3-47e9-4d31-8a87-de45df1122c2"),
                            Age = 72,
                            BirthDate = new DateTime(1951, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Carlo",
                            FootballClubId = 18,
                            ImageUrl = "https://img.a.transfermarkt.technology/portrait/big/16896-1663947412.jpg?lm=1",
                            IsDeleted = false,
                            LastName = "Rossi",
                            Nationality = "Italy"
                        },
                        new
                        {
                            Id = new Guid("c1539dc0-b2dc-4933-8af4-677f30953802"),
                            Age = 82,
                            BirthDate = new DateTime(1941, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Giampaolo",
                            FootballClubId = 20,
                            ImageUrl = "https://img.a.transfermarkt.technology/portrait/big/_1366357924.jpg?lm=1",
                            IsDeleted = false,
                            LastName = "Pozzo",
                            Nationality = "Italy"
                        },
                        new
                        {
                            Id = new Guid("88a88895-c486-47bb-93e9-a0a8edf135bc"),
                            Age = 58,
                            BirthDate = new DateTime(1964, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Joey",
                            FootballClubId = 2,
                            ImageUrl = "https://img.a.transfermarkt.technology/portrait/big/43324-1663930539.jpg?lm=1",
                            IsDeleted = false,
                            LastName = "Saputo",
                            Nationality = "Canada"
                        },
                        new
                        {
                            Id = new Guid("57e1df18-3494-4179-b666-f7f2accc9914"),
                            Age = 73,
                            BirthDate = new DateTime(1949, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Paolo",
                            FootballClubId = 14,
                            ImageUrl = "https://img.a.transfermarkt.technology/portrait/big/13647-1553874773.jpg?lm=1",
                            IsDeleted = false,
                            LastName = "Berlusconi",
                            Nationality = "Italy"
                        },
                        new
                        {
                            Id = new Guid("d18f69d1-4406-4803-b13f-b5c0d390edef"),
                            Age = 45,
                            BirthDate = new DateTime(1978, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Danilo",
                            FootballClubId = 17,
                            ImageUrl = "https://img.a.transfermarkt.technology/portrait/big/104555-1663926110.jpg?lm=1",
                            IsDeleted = false,
                            LastName = "Iervolino",
                            Nationality = "Italy"
                        },
                        new
                        {
                            Id = new Guid("36ed41b3-f7b5-4391-abe2-1306bcdad666"),
                            Age = 65,
                            BirthDate = new DateTime(1958, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Alberto",
                            FootballClubId = 7,
                            ImageUrl = "https://img.a.transfermarkt.technology/portrait/big/98501-1637592266.jpg?lm=1",
                            IsDeleted = false,
                            LastName = "Zangrillo",
                            Nationality = "Italy"
                        },
                        new
                        {
                            Id = new Guid("8f705a22-54ec-4dd1-88d9-69e99e771b4a"),
                            Age = 48,
                            BirthDate = new DateTime(1975, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Saverio",
                            FootballClubId = 12,
                            ImageUrl = "https://img.a.transfermarkt.technology/portrait/big/78495-1586856165.jpg?lm=1",
                            IsDeleted = false,
                            LastName = "Sticchi Damiani",
                            Nationality = "Italy"
                        },
                        new
                        {
                            Id = new Guid("e8bee67e-e0ed-4789-a308-0b1bf5e6b0b6"),
                            Age = 62,
                            BirthDate = new DateTime(1960, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Fabrizio",
                            FootballClubId = 4,
                            ImageUrl = "https://img.a.transfermarkt.technology/portrait/big/16891-1663929957.jpg?lm=1",
                            IsDeleted = false,
                            LastName = "Corsi",
                            Nationality = "Italy"
                        },
                        new
                        {
                            Id = new Guid("0b420965-da31-415c-a42f-137d63b449de"),
                            Age = 60,
                            BirthDate = new DateTime(1963, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Maurizio",
                            FootballClubId = 8,
                            ImageUrl = "https://img.a.transfermarkt.technology/portrait/big/31168-1663949590.jpg?lm=1",
                            IsDeleted = false,
                            LastName = "Setti",
                            Nationality = "Italy"
                        },
                        new
                        {
                            Id = new Guid("447a5a8d-9354-4d65-a452-6be8135bb074"),
                            Age = 46,
                            BirthDate = new DateTime(1977, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Tommaso",
                            FootballClubId = 3,
                            ImageUrl = "https://img.a.transfermarkt.technology/portrait/big/35327-1419868018.jpg?lm=1",
                            IsDeleted = false,
                            LastName = "Giulini",
                            Nationality = "Italy"
                        },
                        new
                        {
                            Id = new Guid("094caad9-570a-4a4d-81f7-ce2141ad8c48"),
                            Age = 65,
                            BirthDate = new DateTime(1958, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Maurizio",
                            FootballClubId = 6,
                            ImageUrl = "https://img.a.transfermarkt.technology/portrait/big/16894-1454497522.jpg?lm=1",
                            IsDeleted = false,
                            LastName = "Stirpe",
                            Nationality = "Italy"
                        });
                });

            modelBuilder.Entity("Calciolandia_Website.Core.Data.Models.Stadium", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Stadiums");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Piazzale Angelo Moratti, 20151 Milan MI",
                            Capacity = 80018,
                            City = "Milan",
                            ImageUrl = "https://img.legaseriea.it/vimages/632b5612/775454473ML003_FC_Internazi.JPG?webp&q=70&size=999x-",
                            IsDeleted = false,
                            Name = "Giuseppe Meazza"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Viale dei Gladiatori, 00135 Roma RM",
                            Capacity = 73261,
                            City = "Rome",
                            ImageUrl = "https://img.legaseriea.it/vimages/635a8731/stadio-olimpico-roma.png?webp&q=70&size=999x-",
                            IsDeleted = false,
                            Name = "Olimpico"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Viale Giulio Cesare, 18, 24124 Bergamo BG",
                            Capacity = 19768,
                            City = "Bergamo",
                            ImageUrl = "https://img.legaseriea.it/vimages/62cef799/7%20(1).jpg?webp&q=70&size=999x-",
                            IsDeleted = false,
                            Name = "Gewiss Stadium"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Via Andrea Costa, 174, 40134 Bologna BO",
                            Capacity = 38279,
                            City = "Bologna",
                            ImageUrl = "https://img.legaseriea.it/vimages/62d9651c/dallara_bologna.png?webp&q=70&size=999x-",
                            IsDeleted = false,
                            Name = "Renato Dall' Ara"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Via Raimondo Carta Raspi, 09126 Cagliari CA",
                            Capacity = 16416,
                            City = "Cagliari",
                            ImageUrl = "https://img.legaseriea.it/vimages/649d9299/unipol%20domus%203.jpg?webp&q=70&size=999x-",
                            IsDeleted = false,
                            Name = "Unipol Domus"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Via delle Olimpiadi, 50053 Empoli FI",
                            Capacity = 19847,
                            City = "Empoli",
                            ImageUrl = "https://img.legaseriea.it/vimages/6346b2cf/EMPOLISITO.png?webp&q=70&size=999x-",
                            IsDeleted = false,
                            Name = "Castellani Computer Gross Arena"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Viale Manfredo Fanti, 4, 50137 Firenze FI",
                            Capacity = 47282,
                            City = "Florence",
                            ImageUrl = "https://img.legaseriea.it/vimages/632865d1/208879_0001_3764373.png?webp&q=70&size=999x-",
                            IsDeleted = false,
                            Name = "Artemio Franchi"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Viale Olimpia, 03100 Frosinone FR",
                            Capacity = 16227,
                            City = "Frozinone",
                            ImageUrl = "https://img.legaseriea.it/vimages/649d7c5a/stadio-benito-stirpe.png?webp&q=70&size=999x-",
                            IsDeleted = false,
                            Name = "Benito Stirpe"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Via Giovanni de Prà, 1, 16139",
                            Capacity = 36348,
                            City = "Genoa",
                            ImageUrl = "https://img.legaseriea.it/vimages/64a2c8bb/IMG_3486.jpg?webp&q=70&size=999x-",
                            IsDeleted = false,
                            Name = "Luigi Ferraris"
                        },
                        new
                        {
                            Id = 10,
                            Address = "Piazzale Olimpia,2,37138 Verona VR",
                            Capacity = 39211,
                            City = "Verona",
                            ImageUrl = "https://img.legaseriea.it/vimages/62d9745c/stadio_03verona.jpg?webp&q=70&size=999x-",
                            IsDeleted = false,
                            Name = "Marcantonio Bentegodi"
                        },
                        new
                        {
                            Id = 11,
                            Address = "Corso Gaetano Scirea, 50, 10151 Torino TO",
                            Capacity = 41507,
                            City = "Turin",
                            ImageUrl = "https://img.legaseriea.it/vimages/62d965db/allianz-stadium.jpg?webp&q=70&size=999x-",
                            IsDeleted = false,
                            Name = "Allianz Stadium"
                        },
                        new
                        {
                            Id = 12,
                            Address = "Viale Stadio, 73024 Lecce LE",
                            Capacity = 31559,
                            City = "Lecce",
                            ImageUrl = "https://img.legaseriea.it/vimages/63564923/STADIO-LECCE.png?webp&q=70&size=999x-",
                            IsDeleted = false,
                            Name = "Ettore Giardiniero - Via Del Mare"
                        },
                        new
                        {
                            Id = 13,
                            Address = "Via Franco Tognini, 4, 20900 Monza MB",
                            Capacity = 15039,
                            City = "Monza",
                            ImageUrl = "https://img.legaseriea.it/vimages/635647a2/STADIO-MONZA.png?webp&q=70&size=999x-",
                            IsDeleted = false,
                            Name = "U-Power Stadium"
                        },
                        new
                        {
                            Id = 14,
                            Address = "Piazzale Vincenzo Tecchio, 80125 Napoli NA",
                            Capacity = 54726,
                            City = "Naples",
                            ImageUrl = "https://img.legaseriea.it/vimages/62da938f/stadio-maradona%20dettaglio-curva.jpg?webp&q=70&size=999x-",
                            IsDeleted = false,
                            Name = "Diego Armando Maradona"
                        },
                        new
                        {
                            Id = 15,
                            Address = "Via Salvador Allende, 84131 Salerno SA",
                            Capacity = 30739,
                            City = "Salerno",
                            ImageUrl = "https://img.legaseriea.it/vimages/63564996/STADIO-ARECHI.png?webp&q=70&size=999x-",
                            IsDeleted = false,
                            Name = "Arechi"
                        },
                        new
                        {
                            Id = 16,
                            Address = "Piazzale Atleti Azzurri D`Italia, 1, 42122 Reggio Emilia RE",
                            Capacity = 21584,
                            City = "Reggio Emilia",
                            ImageUrl = "https://img.legaseriea.it/vimages/635648b4/STADIO-MAPEI.png?webp&q=70&size=999x-",
                            IsDeleted = false,
                            Name = "Mapei Stadium - Citta Del Tricolore"
                        },
                        new
                        {
                            Id = 17,
                            Address = "Via Filadelfia, 96/b, 10134 Torino TO",
                            Capacity = 27994,
                            City = "Turin",
                            ImageUrl = "https://img.legaseriea.it/vimages/6346b263/TORINOSITO.png?webp&q=70&size=999x-",
                            IsDeleted = false,
                            Name = "Olimpico Grande Torino"
                        },
                        new
                        {
                            Id = 18,
                            Address = "Viale Agostino ed Angelo Candolini, 2 , 33100 Udine UD",
                            Capacity = 25144,
                            City = "Udine",
                            ImageUrl = "https://img.legaseriea.it/vimages/64a7e2b8/udinese-stadio.png?webp&q=70&size=999x-",
                            IsDeleted = false,
                            Name = "Udinese Arena"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("469c79e1-d881-4c0b-952f-f08af274800d"),
                            ConcurrencyStamp = "e0519b69-392d-4f6c-92a4-2050215ad104",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("35e824bf-a9ff-4dfa-9cd7-e0bb181ee50a"),
                            RoleId = new Guid("469c79e1-d881-4c0b-952f-f08af274800d")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Calciolandia_Website.Core.Data.Models.ApplicationUser", b =>
                {
                    b.HasOne("Calciolandia_Website.Core.Data.Models.FootballClub", "FootballClub")
                        .WithMany()
                        .HasForeignKey("FootballClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FootballClub");
                });

            modelBuilder.Entity("Calciolandia_Website.Core.Data.Models.Fixture", b =>
                {
                    b.HasOne("Calciolandia_Website.Core.Data.Models.FootballClub", "AwayTeam")
                        .WithMany("AwayFixtures")
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Calciolandia_Website.Core.Data.Models.FootballClub", "HomeTeam")
                        .WithMany("HomeFixtures")
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Calciolandia_Website.Core.Data.Models.League", "League")
                        .WithMany("Fixtures")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Calciolandia_Website.Core.Data.Models.Stadium", "Stadium")
                        .WithMany("Fixtures")
                        .HasForeignKey("StadiumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");

                    b.Navigation("League");

                    b.Navigation("Stadium");
                });

            modelBuilder.Entity("Calciolandia_Website.Core.Data.Models.FootballClub", b =>
                {
                    b.HasOne("Calciolandia_Website.Core.Data.Models.League", "League")
                        .WithMany("FootballClubs")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Calciolandia_Website.Core.Data.Models.Stadium", "Stadium")
                        .WithMany("FootballClubs")
                        .HasForeignKey("StadiumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");

                    b.Navigation("Stadium");
                });

            modelBuilder.Entity("Calciolandia_Website.Core.Data.Models.Manager", b =>
                {
                    b.HasOne("Calciolandia_Website.Core.Data.Models.FootballClub", "FootballClub")
                        .WithMany("Managers")
                        .HasForeignKey("FootballClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FootballClub");
                });

            modelBuilder.Entity("Calciolandia_Website.Core.Data.Models.Player", b =>
                {
                    b.HasOne("Calciolandia_Website.Core.Data.Models.FootballClub", "FootballClub")
                        .WithMany("Players")
                        .HasForeignKey("FootballClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FootballClub");
                });

            modelBuilder.Entity("Calciolandia_Website.Core.Data.Models.President", b =>
                {
                    b.HasOne("Calciolandia_Website.Core.Data.Models.FootballClub", "FootballClub")
                        .WithMany("Presidents")
                        .HasForeignKey("FootballClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FootballClub");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Calciolandia_Website.Core.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Calciolandia_Website.Core.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Calciolandia_Website.Core.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Calciolandia_Website.Core.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Calciolandia_Website.Core.Data.Models.FootballClub", b =>
                {
                    b.Navigation("AwayFixtures");

                    b.Navigation("HomeFixtures");

                    b.Navigation("Managers");

                    b.Navigation("Players");

                    b.Navigation("Presidents");
                });

            modelBuilder.Entity("Calciolandia_Website.Core.Data.Models.League", b =>
                {
                    b.Navigation("Fixtures");

                    b.Navigation("FootballClubs");
                });

            modelBuilder.Entity("Calciolandia_Website.Core.Data.Models.Stadium", b =>
                {
                    b.Navigation("Fixtures");

                    b.Navigation("FootballClubs");
                });
#pragma warning restore 612, 618
        }
    }
}
